:os:
  - "Windows 10"
  - "Windows 8.1"
  - "Windows 8"
  - "Windows 7"
  - "Windows XP"
  - "Linux"
  - "OS X 10.11"
  - "OS X 10.10"
  - "OS X 10.9"
  - "OS X 10.8"
:browser:
  :chrome:
    - "46"
    - "47"
    - "48"
    - "49"
    - "50"
    - "51"
    - "52"
    - "53"
    - "54"
    - "beta"
    - "dev"
  :firefox:
    - "35"
    - "36"
    - "37"
    - "38"
    - "39"
    - "40"
    - "41"
    - "42"
    - "43"
    - "44"
    - "45"
  :ie:
    - "26"
    - "27"
    - "28"
    - "29"
    - "30"
    - "31"
    - "32"
    - "33"
    - "34"
  :edge:
    - "14.14393"
    - "13.10586"
